Allow multiple source pools to be specified
Multiple pools can now be specified as a comma-separated list. It's
also possible to omit the source pool - in that case, the destination
pool(s) must also be omitted, and the result is to mirror from all
local pools to all configured destinations.

diff --git a/zfs-mirror b/zfs-mirror
--- a/zfs-mirror
+++ b/zfs-mirror
@@ -644,7 +644,10 @@ function mirror {
 
 function display_help {
 cat <<EOF
-Usage: zfs-mirror [options] <source pool> [destination pool(s)]
+Usage: zfs-mirror [options] [source pool(s)] [destination pool(s)]
+
+Source should be specified in the form "pool[,pool...]".
+  Default is all pools found on the local system.
 
 Destination should be specified in the form "hostname:pool[,hostname:pool...]"
   Default is all destinations configured for any datasets on the specified
@@ -844,44 +847,43 @@ if [[ $VERBOSE -ge 3 ]] || $AGE_REPORTING; then
     fi
 fi
 
-if [[ $# -eq 0 ]]; then
-    error "You must specify a source pool\nSee '$0 -h' for more information" $ERR_SRC_POOL_MISSING
-fi
-SRC=$1
+SOURCE_POOLS=${1:-$($LOCAL_ZPOOL list -H -o name)}
 
-if ! dataset_exists localhost:$SRC; then
-    error "Couldn't find source pool '$SRC'" $ERR_SRC_POOL_MISSING
-fi
-
-DESTS=${2:-$(get_dest_pools $SRC)}
-
-SRC_LOCKFILE=$(pool_lockfile $SRC)
-DEST_LOCKFILE=""
-
-trap 'cleanup $?' INT TERM EXIT
-
-for DEST in $(split $DESTS); do
-    DEST_LOCKFILE=$(pool_lockfile $DEST)
-
-    if [[ $(echo $DEST | cut -d: -f1) != "localhost" ]] && [[ ! -x $(which $SSH) ]]; then
-        error "'$SSH' not found"
-    fi
-    if ! dataset_exists $DEST; then
-        warn "Couldn't find pool $DEST"
-        status=$ERR_DEST_POOL_MISSING
-        continue
+for SRC in $(split $SOURCE_POOLS); do
+    if ! dataset_exists localhost:$SRC; then
+        error "Couldn't find source pool '$SRC'" $ERR_SRC_POOL_MISSING
     fi
 
-    if $LOG_SIZES_TO_FILE; then
-        # Change the colon to an underscore for ease of transporting to Windows.
-        SIZE_LOG_PATH="/var/log/zfs-mirror-est-send-sizes-${SRC}-to-${DEST//:/_}.log"
-    fi
+    DESTS=${2:-$(get_dest_pools $SRC)}
 
-    if $AGE_REPORTING; then
-        age_report $SRC $DEST
-    else
-        mirror $SRC $DEST || status=$?
-    fi
+    SRC_LOCKFILE=$(pool_lockfile $SRC)
+    DEST_LOCKFILE=""
+
+    trap 'cleanup $?' INT TERM EXIT
+
+    for DEST in $(split $DESTS); do
+        DEST_LOCKFILE=$(pool_lockfile $DEST)
+
+        if [[ $(echo $DEST | cut -d: -f1) != "localhost" ]] && [[ ! -x $(which $SSH) ]]; then
+            error "'$SSH' not found"
+        fi
+        if ! dataset_exists $DEST; then
+            warn "Couldn't find pool $DEST"
+            status=$ERR_DEST_POOL_MISSING
+            continue
+        fi
+
+        if $LOG_SIZES_TO_FILE; then
+            # Change the colon to an underscore for ease of transporting to Windows.
+            SIZE_LOG_PATH="/var/log/zfs-mirror-est-send-sizes-${SRC}-to-${DEST//:/_}.log"
+        fi
+
+        if $AGE_REPORTING; then
+            age_report $SRC $DEST
+        else
+            mirror $SRC $DEST || status=$?
+        fi
+    done
 done
 
 # If there were any errors not quite severe enough to terminate the process
