Don't implicitly try invalid src/dest combinations
Previously when a user requested a destination but no source, we would
try sending to that destination from *all* potential sources, producing
a warning when an implicitly created source/destination pair was
invalid.

If a user *explicitly* requested an invalid source/destination pair,
this probably represents a mistake, and so we do want to check and
report these. On the other hand, if a user simply selects a destination,
then we need to determine the sources that are configured to actually
use it.

diff --git a/zfs-mirror b/zfs-mirror
--- a/zfs-mirror
+++ b/zfs-mirror
@@ -31,6 +31,7 @@ AGE_WARNING_SECONDS_DEFAULT=$((60 * 60 * 24))
 BWLIMIT=""
 COLOUR="auto"
 COMPRESS=false
+EXPLICIT_SOURCE_AND_DEST=false
 GET_DESTS=false
 INC_OPT="-i"
 KEEP_DEST=10
@@ -1014,6 +1015,7 @@ case $# in
         if [[ $1 != *:* ]] && [[ $2 == *:* ]]; then
             SOURCES=$1
             DESTS=$2
+            EXPLICIT_SOURCE_AND_DEST=true
         else
             error "Invalid source/dest pool combination ($1/$2)\nSee '$0 -h' for more information" $ERR_INVALID_ARGUMENT
         fi
@@ -1041,24 +1043,26 @@ else
         for DEST in $(split $DESTS); do
             DEST_LOCKFILE=$(pool_lockfile $SRC-to-$DEST)
 
-            if [[ $(echo $DEST | cut -d: -f1) != "localhost" ]] && [[ ! -x $(which $SSH) ]]; then
-                error "'$SSH' not found"
-            fi
-            if ! dataset_exists $DEST; then
-                warn "Couldn't find dest pool $DEST"
-                STATUS=$ERR_DEST_POOL_MISSING
-                continue
-            fi
+            if $EXPLICIT_SOURCE_AND_DEST || [[ $(get_source_filesystems $DEST) != "" ]]; then
+                if [[ $(echo $DEST | cut -d: -f1) != "localhost" ]] && [[ ! -x $(which $SSH) ]]; then
+                    error "'$SSH' not found"
+                fi
+                if ! dataset_exists $DEST; then
+                    warn "Couldn't find dest pool $DEST"
+                    STATUS=$ERR_DEST_POOL_MISSING
+                    continue
+                fi
 
-            if $LOG_SIZES_TO_FILE; then
-                # Change the colon to an underscore for ease of transporting to Windows.
-                SIZE_LOG_PATH="/var/log/zfs-mirror-est-send-sizes-${SRC}-to-${DEST//:/_}.log"
-            fi
+                if $LOG_SIZES_TO_FILE; then
+                    # Change the colon to an underscore for ease of transporting to Windows.
+                    SIZE_LOG_PATH="/var/log/zfs-mirror-est-send-sizes-${SRC}-to-${DEST//:/_}.log"
+                fi
 
-            if $AGE_REPORTING; then
-                age_report $SRC $DEST
-            else
-                mirror $SRC $DEST || STATUS=$?
+                if $AGE_REPORTING; then
+                    age_report $SRC $DEST
+                else
+                    mirror $SRC $DEST || STATUS=$?
+                fi
             fi
         done
     done
