Rename local $error to $error_msg
To avoid shadowing the global 'error' function.

diff --git a/zfs-mirror b/zfs-mirror
--- a/zfs-mirror
+++ b/zfs-mirror
@@ -446,22 +446,22 @@ function zfs_try_send_incr {
     # $5 destination pool
     trace $FUNCNAME $@
     local pv=$(get_pv_cmd -i @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3)
-    local error=$(do_conditionally "$LOCAL_ZFS send $ZFS_VERBOSE $ZFS_SEND_DEDUP -i @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 | $pv $4 receive $ZFS_VERBOSE -ud $5 2>&1 || true")
-    error=${error%%\\r}
-    if [[ $error != "" ]]; then
-        if [[ $error == "cannot receive incremental stream: invalid backup stream" ]]; then
-            log "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error). Retrying:"
-            error=$(do_conditionally "$LOCAL_ZFS send $ZFS_VERBOSE $ZFS_SEND_DEDUP -i @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 | $pv $4 receive $ZFS_VERBOSE -ud $5 2>&1 || true")
-            if [[ $error != "" ]]; then
-                warn "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error)"
+    local error_msg=$(do_conditionally "$LOCAL_ZFS send $ZFS_VERBOSE $ZFS_SEND_DEDUP -i @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 | $pv $4 receive $ZFS_VERBOSE -ud $5 2>&1 || true")
+    error_msg=${error_msg%%\\r}
+    if [[ $error_msg != "" ]]; then
+        if [[ $error_msg == "cannot receive incremental stream: invalid backup stream" ]]; then
+            log "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error_msg). Retrying:"
+            error_msg=$(do_conditionally "$LOCAL_ZFS send $ZFS_VERBOSE $ZFS_SEND_DEDUP -i @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 | $pv $4 receive $ZFS_VERBOSE -ud $5 2>&1 || true")
+            if [[ $error_msg != "" ]]; then
+                warn "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error_msg)"
             else
                 log "Retry successful"
             fi
         else
-            warn "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error)"
+            warn "Error sending @"$SNAPSHOT_PREFIX"_$2 $1@"$SNAPSHOT_PREFIX"_$3 ($error_msg)"
         fi
     fi
-    echo $error
+    echo $error_msg
 }
 
 function zfs_send_incr {
@@ -481,9 +481,9 @@ function zfs_send_incr {
             local dest_zfs="$XZSEND $BWLIMIT $SSH $dest_host $XZRECV zfs"
         fi
     fi
-    local error=$(zfs_try_send_incr $1 $3 $4 "$dest_zfs" "$dest_pool")
-    if [[ $error != "" ]]; then
-        if [[ $error == "cannot receive incremental stream: invalid backup stream" ]] && [[ $4 -gt $(( $3 + 1 )) ]]; then
+    local error_msg=$(zfs_try_send_incr $1 $3 $4 "$dest_zfs" "$dest_pool")
+    if [[ $error_msg != "" ]]; then
+        if [[ $error_msg == "cannot receive incremental stream: invalid backup stream" ]] && [[ $4 -gt $(( $3 + 1 )) ]]; then
             warn "Attempting to send intervening snapshots one-by-one:"
             local intervening_snapshots=$($LOCAL_ZFS list -H -d 1 -r -o name -s name -t snapshot $1 2> /dev/null | $GREP @"$SNAPSHOT_PREFIX"_ | sed -e "s/.*@$SNAPSHOT_PREFIX\_//" | sort -n)
             local prev=$3
@@ -491,8 +491,8 @@ function zfs_send_incr {
                 if [[ $snapshot -le $prev ]]; then
                     continue
                 fi
-                error=$(zfs_try_send_incr $1 $prev $snapshot "$dest_zfs" "$dest_pool")
-                if [[ $error != "" ]]; then
+                error_msg=$(zfs_try_send_incr $1 $prev $snapshot "$dest_zfs" "$dest_pool")
+                if [[ $error_msg != "" ]]; then
                     break
                 fi
                 prev=$snapshot
