Rename global variable $status to $STATUS

diff --git a/zfs-mirror b/zfs-mirror
--- a/zfs-mirror
+++ b/zfs-mirror
@@ -869,7 +869,7 @@ for SRC in $(split $SOURCE_POOLS); do
         fi
         if ! dataset_exists $DEST; then
             warn "Couldn't find pool $DEST"
-            status=$ERR_DEST_POOL_MISSING
+            STATUS=$ERR_DEST_POOL_MISSING
             continue
         fi
 
@@ -881,11 +881,11 @@ for SRC in $(split $SOURCE_POOLS); do
         if $AGE_REPORTING; then
             age_report $SRC $DEST
         else
-            mirror $SRC $DEST || status=$?
+            mirror $SRC $DEST || STATUS=$?
         fi
     done
 done
 
 # If there were any errors not quite severe enough to terminate the process
-# entirely, $status holds the error code for the *most recent* failure.
-exit ${status:-0}
+# entirely, $STATUS holds the error code for the *most recent* failure.
+exit ${STATUS:-0}
